production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING

cucumber:
  solr:
    hostname: localhost
    port: <%= 8164 + ENV['TEST_ENV_NUMBER'].to_i %>
    log_level: INFO
    data_path: <%= File.join(::Rails.root, 'solr', 'data', ::Rails.env, ENV['TEST_ENV_NUMBER'].to_i.to_s) %>
    pid_dir: <%= File.join(::Rails.root, 'solr', 'pids', ::Rails.env, ENV['TEST_ENV_NUMBER'].to_i.to_s) %>
    auto_commit_after_request: false
    auto_commit_after_delete_request: false
